import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Observable, of } from 'rxjs';
import { debounceTime, distinctUntilChanged, startWith, switchMap } from 'rxjs/operators';

@Component({
  selector: 'app-field-properties-modal',
  templateUrl: './field-properties-modal.component.html',
  styleUrls: ['./field-properties-modal.component.scss']
})
export class FieldPropertiesModalComponent implements OnInit {
  @Input() mode: 'add' | 'edit' = 'add';
  @Input() propertyData: any = null;
  @Output() save = new EventEmitter<any>();
  @Output() cancel = new EventEmitter<void>();

  propertyForm: FormGroup;
  filteredKeys$!: Observable<string[]>;

  successMessage: string | null = null;
  errorMessage: string | null = null;

  constructor(private fb: FormBuilder) {
    this.propertyForm = this.fb.group({
      key: ['', Validators.required],
      fieldDataType: ['String', Validators.required],
      fieldValueType: [''],
      fieldGenerationType: [''],
      fieldFormat: [''],
      isMandatory: [false],
      autoGenerated: [false]
    });
  }

  ngOnInit(): void {
    if (this.mode === 'edit' && this.propertyData) {
      // API CALL: GET /api/contracts/fields/{id} (to fetch specific field metadata).
      this.propertyForm.patchValue(this.propertyData);
    }

    this.filteredKeys$ = this.propertyForm.get('key')!.valueChanges.pipe(
      startWith(''),
      debounceTime(300),
      distinctUntilChanged(),
      switchMap(value => this.fetchKeys(value || ''))
    );
  }

  private fetchKeys(searchTerm: string): Observable<string[]> {
    if (!searchTerm) {
      return of([]);
    }
    // API CALL: GET /api/contracts/keys/lookup?query={searchTerm}.
    // Sample Implementation:
    // return this.http.get<string[]>(`/api/contracts/keys/lookup?query=${searchTerm}`);

    const mockKeys = ['userId', 'userName', 'email', 'createdAt', 'updatedAt', 'status', 'roles', 'profile'];
    return of(mockKeys.filter(key => key.toLowerCase().includes(searchTerm.toLowerCase())));
  }

  private triggerAlert(type: 'success' | 'error', message: string) {
    if (type === 'success') {
      this.successMessage = message;
      this.errorMessage = null;
    } else {
      this.errorMessage = message;
      this.successMessage = null;
    }

    setTimeout(() => {
      this.successMessage = null;
      this.errorMessage = null;
    }, 5000);
  }

  onSave(): void {
    if (this.propertyForm.valid) {
      const data = this.propertyForm.value;
      // API CALL: POST /api/contracts/fields/validate (to check for duplicate keys).

      this.triggerAlert('success', 'Property saved successfully!');

      // ERROR: Set errorMessage (Placeholder for API failures)
      // this.triggerAlert('error', 'Failed to save property. Please try again.');

      setTimeout(() => {
        this.save.emit(data);
      }, 5000);
    } else {
      this.propertyForm.markAllAsTouched();
    }
  }

  onCancel(): void {
    this.cancel.emit();
  }
}
