import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Observable, of } from 'rxjs';
import { ErrorMessageService } from 'src/app/services/error-message.service';
import { debounceTime, distinctUntilChanged, startWith, switchMap } from 'rxjs/operators';
import { flatten } from 'flat';

@Component({
  selector: 'app-field-properties-modal',
  templateUrl: './field-properties-modal.component.html',
  styleUrls: ['./field-properties-modal.component.scss']
})
export class FieldPropertiesModalComponent implements OnInit {
  @Input() mode: 'add' | 'edit' = 'add';
  @Input() propertyData: any = null;
  @Input() baseContractJson: any = null;
  @Output() save = new EventEmitter<any>();
  @Output() cancel = new EventEmitter<void>();

  propertyForm: FormGroup;
  filteredKeys$!: Observable<string[]>;

  successMessage: string | null = null;
  errorMessage: string | null = null;

  constructor(
    private fb: FormBuilder,
    private errorMessageService: ErrorMessageService
  ) {
    this.propertyForm = this.fb.group({
      key: ['', Validators.required],
      fieldDataType: ['String', Validators.required],
      fieldValueType: ['', Validators.required],
      fieldGenerationType: ['', Validators.required],
      fieldFormat: [''],
      isMandatory: [false],
      autoGenerated: [false]
    });
  }

  ngOnInit(): void {
    if (this.mode === 'edit' && this.propertyData) {
      this.propertyForm.patchValue(this.propertyData);
    }

    this.filteredKeys$ = this.propertyForm.get('key')!.valueChanges.pipe(
      startWith(''),
      debounceTime(300),
      distinctUntilChanged(),
      switchMap(value => this.fetchKeys(value || ''))
    );

    this.propertyForm.get('fieldGenerationType')?.valueChanges.subscribe(value => {
      const fieldFormatControl = this.propertyForm.get('fieldFormat');
      if (value !== 'DATE_VARIATION$TODAY_DATE') {
        fieldFormatControl?.setValue('', { emitEvent: false });
        fieldFormatControl?.clearValidators();
      } else {
        fieldFormatControl?.setValidators([Validators.required]);
      }
      fieldFormatControl?.updateValueAndValidity();
    });
  }

  private fetchKeys(searchTerm: string): Observable<string[]> {
    const flattenedKeys = this.getFlattenedKeys();

    if (!searchTerm) {
      return of(flattenedKeys.slice(0, 10));
    }

    const filtered = flattenedKeys.filter(key =>
      key.toLowerCase().includes(searchTerm.toLowerCase())
    );

    return of(filtered.slice(0, 10));
  }

  getErrorMessage(field: string, type: string): string {
    return this.errorMessageService.getErrorMessage('MODAL', field, type);
  }

  private getFlattenedKeys(): string[] {
    if (!this.baseContractJson) {
      return [];
    }
    try {
      const flattened: any = flatten(this.baseContractJson);
      return Object.keys(flattened);
    } catch (e) {
      console.error('Failed to flatten JSON in modal:', e);
      return [];
    }
  }

  private triggerAlert(type: 'success' | 'error', message: string) {
    if (type === 'success') {
      this.successMessage = message;
      this.errorMessage = null;
    } else {
      this.errorMessage = message;
      this.successMessage = null;
    }

    setTimeout(() => {
      this.successMessage = null;
      this.errorMessage = null;
    }, 5000);
  }

  onSave(): void {
    if (this.propertyForm.valid) {
      const data = this.propertyForm.value;
      this.triggerAlert('success', 'Property saved successfully!');

      setTimeout(() => {
        this.save.emit(data);
      }, 500); // Reduced delay for better UX in this context
    } else {
      this.propertyForm.markAllAsTouched();
    }
  }

  onCancel(): void {
    this.cancel.emit();
  }
}
