import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-field-properties-modal',
  templateUrl: './field-properties-modal.component.html',
  styleUrls: ['./field-properties-modal.component.scss']
})
export class FieldPropertiesModalComponent implements OnInit {
  @Input() mode: 'add' | 'edit' = 'add';
  @Input() propertyData: any = null;
  @Output() save = new EventEmitter<any>();
  @Output() cancel = new EventEmitter<void>();

  propertyForm: FormGroup;

  constructor(private fb: FormBuilder) {
    this.propertyForm = this.fb.group({
      key: ['', Validators.required],
      fieldDataType: ['String', Validators.required],
      fieldValueType: [''],
      fieldGenerationType: [''],
      fieldFormat: [''],
      isMandatory: [false],
      autoGenerated: [false]
    });
  }

  ngOnInit(): void {
    if (this.mode === 'edit' && this.propertyData) {
      // API CALL: GET /api/contracts/fields/{id} (to fetch specific field metadata).
      this.propertyForm.patchValue(this.propertyData);
    }
  }

  onSave(): void {
    if (this.propertyForm.valid) {
      const data = this.propertyForm.value;
      // API CALL: POST /api/contracts/fields/validate (to check for duplicate keys).
      this.save.emit(data);
    } else {
      this.propertyForm.markAllAsTouched();
    }
  }

  onCancel(): void {
    this.cancel.emit();
  }
}
