import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HeaderService } from '../../services/header.service';

@Component({
  selector: 'app-contract-details',
  templateUrl: './contract-details.component.html',
  styleUrls: ['./contract-details.component.scss']
})
export class ContractDetailsComponent implements OnInit {
  mode: 'new' | 'edit' | 'view' = 'new';
  contractId: string | null = null;
  contractForm: FormGroup;

  // UI State
  schemaMode: 'upload' | 'editor' = 'upload';
  baseContractMode: 'upload' | 'editor' = 'editor';
  isPropertyModalOpen = false;
  propertyModalMode: 'add' | 'edit' = 'add';
  selectedProperty: any = null;
  selectedPropertyIndex: number | null = null;

  configuredFieldProperties: any[] = [
    { key: 'contractId', fieldDataType: 'String', isMandatory: true, autoGenerated: true },
    { key: 'version', fieldDataType: 'String', isMandatory: true, autoGenerated: false },
    { key: 'status', fieldDataType: 'String', isMandatory: false, autoGenerated: false }
  ];

  // Mock Data
  sampleSchema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "contractId": { "type": "string" },
      "version": { "type": "string" },
      "status": { "type": "string" }
    }
  };

  sampleBaseContract = {
    "contractId": "UUID-7821-X",
    "version": "1.0.0",
    "data": {
      "status": "active",
      "params": {}
    }
  };

  constructor(
    private headerService: HeaderService,
    private route: ActivatedRoute,
    private router: Router,
    private fb: FormBuilder
  ) {
    this.contractForm = this.fb.group({
      contractName: ['', Validators.required],
      contractType: ['', Validators.required],
      contractDescription: ['']
    });
  }

  ngOnInit(): void {
    // Mode Detection
    this.route.data.subscribe(data => {
      this.mode = data['mode'] === 'edit' ? 'edit' : 'new';
    });

    this.route.queryParamMap.subscribe(params => {
      const modeParam = params.get('mode');
      if (modeParam === 'view') {
        this.mode = 'view';
      } else if (modeParam === 'edit') {
        this.mode = 'edit';
      }
    });

    this.route.paramMap.subscribe(params => {
      this.contractId = params.get('id');
      if ((this.mode === 'edit' || this.mode === 'view') && this.contractId) {
        this.loadContract(this.contractId);
      }
    });

    if (this.mode === 'view') {
      this.contractForm.disable();
    }

    // Header Service Integration
    const title = this.mode === 'view' ? 'View Contract' : (this.mode === 'edit' ? 'Edit Contract' : 'Contract Details');
    this.headerService.setHeaderData(
      title,
      'Define the structural and baseline data for your test suites by providing schema definitions.'
    );
  }

  loadContract(id: string) {
    // API CALL: GET /api/contracts/{id}
    console.log(`Fetching contract with id: ${id}`);

    // Simulating API response
    const mockResponse = {
      contractName: 'Auth Response Schema',
      contractType: 'Consumer',
      contractDescription: 'Baseline schema for authentication response verification.'
    };
    this.contractForm.patchValue(mockResponse);
  }

  onSave() {
    if (this.contractForm.valid) {
      const formData = this.contractForm.value;
      if (this.mode === 'edit') {
        // API CALL: PUT /api/contracts/{id}
        console.log('Updating contract', this.contractId, formData);
      } else {
        // API CALL: POST /api/contracts
        console.log('Creating new contract', formData);
      }
      window.history.back();
    } else {
      this.contractForm.markAllAsTouched();
    }
  }

  onCancel() {
    window.history.back();
  }

  // LOGIC: File upload handler and JSON validation.
  onFileUpload(event: any) {
    const file = event.target.files[0];
    if (file) {
      console.log('File uploaded:', file.name);
      // Implement file reading and validation logic here
    }
  }

  validateJson(json: string): boolean {
    try {
      JSON.parse(json);
      return true;
    } catch (e) {
      return false;
    }
  }

  // Field Properties Modal Handlers
  openAddPropertyModal() {
    this.propertyModalMode = 'add';
    this.selectedProperty = null;
    this.selectedPropertyIndex = null;
    this.isPropertyModalOpen = true;
  }

  openEditPropertyModal(property: any, index: number) {
    this.propertyModalMode = 'edit';
    this.selectedProperty = { ...property };
    this.selectedPropertyIndex = index;
    this.isPropertyModalOpen = true;
  }

  handlePropertySave(propertyData: any) {
    if (this.propertyModalMode === 'edit' && this.selectedPropertyIndex !== null) {
      this.configuredFieldProperties[this.selectedPropertyIndex] = propertyData;
    } else {
      this.configuredFieldProperties.push(propertyData);
    }
    this.isPropertyModalOpen = false;
  }

  handlePropertyCancel() {
    this.isPropertyModalOpen = false;
  }

  removeProperty(index: number) {
    this.configuredFieldProperties.splice(index, 1);
  }
}
