import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HeaderService } from '../../services/header.service';
import { ErrorMessageService } from '../../services/error-message.service';

@Component({
  selector: 'app-contract-details',
  templateUrl: './contract-details.component.html',
  styleUrls: ['./contract-details.component.scss']
})
export class ContractDetailsComponent implements OnInit {
  mode: 'new' | 'edit' | 'view' = 'new';
  contractId: string | null = null;
  contractForm: FormGroup;

  successMessage: string | null = null;
  errorMessage: string | null = null;

  // UI State
  schemaMode: 'upload' | 'editor' = 'upload';
  baseContractMode: 'upload' | 'editor' = 'editor';
  isPropertyModalOpen = false;
  propertyModalMode: 'add' | 'edit' = 'add';
  selectedProperty: any = null;
  selectedPropertyIndex: number | null = null;

  configuredFieldProperties: any[] = [
    { key: 'contractId', fieldDataType: 'String', isMandatory: true, autoGenerated: true },
    { key: 'version', fieldDataType: 'String', isMandatory: true, autoGenerated: false },
    { key: 'status', fieldDataType: 'String', isMandatory: false, autoGenerated: false }
  ];

  // Mock Data
  sampleSchema = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "contractId": { "type": "string" },
      "version": { "type": "string" },
      "status": { "type": "string" }
    }
  };

  sampleBaseContract = {
    "contractId": "UUID-7821-X",
    "version": "1.0.0",
    "data": {
      "status": "active",
      "params": {}
    }
  };

  constructor(
    private headerService: HeaderService,
    private route: ActivatedRoute,
    private router: Router,
    private fb: FormBuilder,
    private errorMessageService: ErrorMessageService
  ) {
    this.contractForm = this.fb.group({
      contractName: ['', Validators.required],
      contractType: ['', Validators.required],
      description: ['', Validators.required],
      baseContract: [JSON.stringify(this.sampleBaseContract, null, 2), Validators.required]
    });
  }

  ngOnInit(): void {
    // Mode Detection
    this.route.data.subscribe(data => {
      this.mode = data['mode'] === 'edit' ? 'edit' : 'new';
    });

    this.route.queryParamMap.subscribe(params => {
      const modeParam = params.get('mode');
      if (modeParam === 'view') {
        this.mode = 'view';
      } else if (modeParam === 'edit') {
        this.mode = 'edit';
      }
    });

    this.route.paramMap.subscribe(params => {
      this.contractId = params.get('id');
      if ((this.mode === 'edit' || this.mode === 'view') && this.contractId) {
        this.loadContract(this.contractId);
      }
    });

    if (this.mode === 'view') {
      this.contractForm.disable();
    }

    // Header Service Integration
    const title = this.mode === 'view' ? 'View Contract' : (this.mode === 'edit' ? 'Edit Contract' : 'Contract Details');
    this.headerService.setHeaderData(
      title,
      'Define the structural and baseline data for your test suites by providing schema definitions.'
    );
  }

  loadContract(id: string) {
    console.log(`Fetching contract with id: ${id}`);

    // Simulating API response
    const mockResponse = {
      contractName: 'Auth Response Schema',
      contractType: 'Consumer',
      description: 'Baseline schema for authentication response verification.',
      baseContract: JSON.stringify(this.sampleBaseContract, null, 2)
    };
    this.contractForm.patchValue(mockResponse);
  }

  getError(field: string, type: string): string {
    return this.errorMessageService.getErrorMessage('CONTRACT', field, type);
  }

  private triggerAlert(type: 'success' | 'error', message: string) {
    if (type === 'success') {
      this.successMessage = message;
      this.errorMessage = null;
    } else {
      this.errorMessage = message;
      this.successMessage = null;
    }

    setTimeout(() => {
      this.successMessage = null;
      this.errorMessage = null;
    }, 5000);
  }

  onSave() {
    if (this.contractForm.valid) {
      const formData = this.contractForm.value;
      if (this.mode === 'edit') {
        console.log('Updating contract', this.contractId, formData);
        this.triggerAlert('success', 'Contract updated successfully!');
      } else {
        console.log('Creating new contract', formData);
        this.triggerAlert('success', 'Contract created successfully!');
      }

      setTimeout(() => {
        window.history.back();
      }, 2000);
    } else {
      this.contractForm.markAllAsTouched();
      // Ensure fields are marked as dirty for validation styling
      Object.keys(this.contractForm.controls).forEach(key => {
        this.contractForm.get(key)?.markAsDirty();
      });
    }
  }

  onCancel() {
    window.history.back();
  }

  onFileUpload(event: any, field: string) {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e: any) => {
        const content = e.target.result;
        if (this.validateJson(content)) {
          if (field === 'baseContract') {
            this.contractForm.get('baseContract')?.setValue(content);
            this.contractForm.get('baseContract')?.markAsDirty();
          }
          // Handle schema file if needed, but for now we focus on baseContract validation
        } else {
          this.triggerAlert('error', 'Invalid JSON file.');
        }
      };
      reader.readAsText(file);
    }
  }

  validateJson(json: string): boolean {
    try {
      JSON.parse(json);
      return true;
    } catch (e) {
      return false;
    }
  }

  // Field Properties Modal Handlers
  openAddPropertyModal() {
    this.propertyModalMode = 'add';
    this.selectedProperty = null;
    this.selectedPropertyIndex = null;
    this.isPropertyModalOpen = true;
  }

  openEditPropertyModal(property: any, index: number) {
    this.propertyModalMode = 'edit';
    this.selectedProperty = { ...property };
    this.selectedPropertyIndex = index;
    this.isPropertyModalOpen = true;
  }

  handlePropertySave(propertyData: any) {
    if (this.propertyModalMode === 'edit' && this.selectedPropertyIndex !== null) {
      this.configuredFieldProperties[this.selectedPropertyIndex] = propertyData;
    } else {
      this.configuredFieldProperties.push(propertyData);
    }
    this.isPropertyModalOpen = false;
  }

  handlePropertyCancel() {
    this.isPropertyModalOpen = false;
  }

  removeProperty(index: number) {
    this.configuredFieldProperties.splice(index, 1);
  }
}
